In [1]:
import numpy as np
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import Matern
import matplotlib.pyplot as plt
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler
import os


In [2]:
data_path = os.path.join("..", "data")

In [3]:
X = np.load(data_path + '/initial_data/function_7/initial_inputs.npy')
y = np.load(data_path + '/initial_data/function_7/initial_outputs.npy')
print(f"X is:{X}")
print(f"Y is :{y}")

X is:[[0.27262382 0.32449536 0.89710881 0.83295115 0.15406269 0.79586362]
 [0.54300258 0.9246939  0.34156746 0.64648585 0.71844033 0.34313266]
 [0.09083225 0.66152938 0.06593091 0.25857701 0.96345285 0.6402654 ]
 [0.11886697 0.61505494 0.90581639 0.8553003  0.41363143 0.58523563]
 [0.63021764 0.8380969  0.68001305 0.73189509 0.52673671 0.34842921]
 [0.76491917 0.25588292 0.60908422 0.21807904 0.32294277 0.09579366]
 [0.05789554 0.49167222 0.24742222 0.21811844 0.42042833 0.73096984]
 [0.19525188 0.07922665 0.55458046 0.17056682 0.01494418 0.10703171]
 [0.64230298 0.83687455 0.02179269 0.10148801 0.68307083 0.6924164 ]
 [0.78994255 0.19554501 0.57562333 0.07365919 0.25904917 0.05109986]
 [0.52849733 0.45742436 0.36009569 0.36204551 0.81689098 0.63747637]
 [0.72261522 0.01181284 0.06364591 0.16517311 0.07924415 0.35995166]
 [0.07566492 0.33450212 0.13273274 0.60831236 0.91838592 0.82233079]
 [0.94245084 0.37743962 0.48612233 0.22879108 0.08263175 0.71195755]
 [0.14864702 0.03394336 0.728

In [4]:
# add the week 1 input and  result to the array
X = np.append(X, [[0.151199, 0.033732, 0.730708, 0.344778, 0.023911, 0.533736]], axis=0)
y = np.append(y, [0.62260079], axis=0)

# add the week 2 input and result to the array
X = np.append(X, [[0.023952, 0.436365, 0.285535, 0.137788, 0.353289, 0.747301]], axis=0)
y = np.append(y, [1.515243229538322], axis=0)

# add the week 3 input and result to the array
X = np.append(X, [[0.025165, 0.343159, 0.324152, 0.113682, 0.321857, 0.924456]], axis=0)
y = np.append(y, [1.0711503490830157], axis=0)

# add the week 4 input and result to the array
X = np.append(X, [[0.003259, 0.392839, 0.309986, 0.034139, 0.323222, 0.843995]], axis=0)
y = np.append(y, [0.9336738018455746], axis=0)

# add the week 5 input and result to the array
X = np.append(X, [[0.005966, 0.408227, 0.235281, 0.257264, 0.364575, 0.611106]], axis=0)
y = np.append(y, [1.8597476940165774], axis=0)

# add the week 6 input and result to the array
X = np.append(X, [[0.012847, 0.337198, 0.189260, 0.238606, 0.359323, 0.557438]], axis=0)
y = np.append(y, [1.8838079567704533], axis=0)

# add the week 7 input and result to the array
X = np.append(X, [[0.005938, 0.357099, 0.254090, 0.226019, 0.373983, 0.567737]], axis=0)
y = np.append(y, [1.8684324311018121], axis=0)

print(f"X is:{X}")
print(f"Y is :{y}")

X is:[[0.27262382 0.32449536 0.89710881 0.83295115 0.15406269 0.79586362]
 [0.54300258 0.9246939  0.34156746 0.64648585 0.71844033 0.34313266]
 [0.09083225 0.66152938 0.06593091 0.25857701 0.96345285 0.6402654 ]
 [0.11886697 0.61505494 0.90581639 0.8553003  0.41363143 0.58523563]
 [0.63021764 0.8380969  0.68001305 0.73189509 0.52673671 0.34842921]
 [0.76491917 0.25588292 0.60908422 0.21807904 0.32294277 0.09579366]
 [0.05789554 0.49167222 0.24742222 0.21811844 0.42042833 0.73096984]
 [0.19525188 0.07922665 0.55458046 0.17056682 0.01494418 0.10703171]
 [0.64230298 0.83687455 0.02179269 0.10148801 0.68307083 0.6924164 ]
 [0.78994255 0.19554501 0.57562333 0.07365919 0.25904917 0.05109986]
 [0.52849733 0.45742436 0.36009569 0.36204551 0.81689098 0.63747637]
 [0.72261522 0.01181284 0.06364591 0.16517311 0.07924415 0.35995166]
 [0.07566492 0.33450212 0.13273274 0.60831236 0.91838592 0.82233079]
 [0.94245084 0.37743962 0.48612233 0.22879108 0.08263175 0.71195755]
 [0.14864702 0.03394336 0.728

In [5]:
print(f"max y is :{np.max(y)}")

max y is :1.8838079567704533


In [6]:
# Define GP model
kernel = Matern(nu=2.5, length_scale_bounds=(1e-2, 1e2))
gp = GaussianProcessRegressor(kernel=kernel, alpha=1e-10, normalize_y=True)
gp.fit(X, y)

GaussianProcessRegressor(kernel=Matern(length_scale=1, nu=2.5),
                         normalize_y=True)

In [7]:
# UCB acquisition function
# week 6 changed kappa to 4.0 from 2.0
def ucb(x, gp, kappa=4.0):
    x = x.reshape(1, -1)
    mu, sigma = gp.predict(x, return_std=True)
    return mu + kappa * sigma

In [8]:
n_samples = 3000000  # You can adjust this based on your compute budget

# Generate random 6D points in [0, 1]^6
X_random = np.random.rand(n_samples, 6)

In [9]:
ucb_values = np.array([ucb(x, gp) for x in X_random])


In [10]:
best_idx = np.argmax(ucb_values)
# next_best_point = X_grid[best_idx]
next_best_point = X_random[best_idx]
print("Next best point to evaluate (UCB) rounded:", np.round(next_best_point,6))
print("Next best point to evaluate (UCB):", next_best_point)
pred_mean, pred_std = gp.predict(next_best_point.reshape(1, -1), return_std=True)
print("Predicted maximum value (mean):", pred_mean[0])

Next best point to evaluate (UCB) rounded: [0.004029 0.00812  0.157955 0.418604 0.120639 0.793899]
Next best point to evaluate (UCB): [0.00402904 0.00811957 0.15795529 0.41860351 0.12063855 0.79389942]
Predicted maximum value (mean): 1.1514750672758558


In [11]:
# SVM model as surrogate
# Scale inputs
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Train SVM surrogate
svm_surrogate = SVR(kernel='rbf', C=15.0, epsilon=0.1)
svm_surrogate.fit(X_scaled, y)

# Predict on new candidates
X_new = np.random.rand(10000000, 6)
X_new_scaled = scaler.transform(X_new)
y_pred = svm_surrogate.predict(X_new_scaled)

# Maximization: find best candidate
best_idx = np.argmax(y_pred)
best_candidate = X_new[best_idx]
best_predicted_value = y_pred[best_idx]

print("Best candidate input:", best_candidate)
print("Best candidate input rounded:", np.round(best_candidate, 6))
print("Predicted maximum value:", best_predicted_value)

Best candidate input: [0.00568991 0.36159399 0.23277261 0.26005434 0.43548034 0.53005964]
Best candidate input rounded: [0.00569  0.361594 0.232773 0.260054 0.43548  0.53006 ]
Predicted maximum value: 1.7831573756905055
